New version adding
Mih-Mir/WriteFromCsvToDatabase pull request #2
Opened 2021-06-22 16:48 UTC by Mih-Mir

2021-06-22 18:17 UTC, sachenko-igor requested changes

2021-06-22 18:17 UTC, sachenko-igor commented on WriteFromCsvToDatabase/Services/ChunkDataLoader.cs
> +                    using (var reader = ObjectReader.Create(bucket.ToList()))
What is ObjectReader? Looks like this is the same thing like your ModelDataReader

2021-06-22 18:17 UTC, sachenko-igor commented on WriteFromCsvToDatabase/Services/ChunkDataLoader.cs
> +                    using (var reader = ObjectReader.Create(bucket.ToList()))
In this case, this is not what I wanted you to implement. Use a data table to load the data. But remember this approach for the future. It is interesting.

2021-06-22 19:29 UTC, Mih-Mir commented on WriteFromCsvToDatabase/Services/ChunkDataLoader.cs
> +                    using (var reader = ObjectReader.Create(bucket.ToList()))
Done

2021-06-23 07:58 UTC, sachenko-igor requested changes

2021-06-23 07:58 UTC, sachenko-igor commented on WriteFromCsvToDatabase/Services/ChunkDataLoader.cs
>              var dataTable = new DataTable();
Move this logic about creating of DataTable into a separate method. 
It is fine to duplicate the logic of the creation of the DataTable Columns etc. Don't call DataTable.Clear. Just keep it as is. It will be cleared by GC.

2021-06-23 07:58 UTC, sachenko-igor commented on WriteFromCsvToDatabase/Services/ChunkDataLoader.cs
>              var dataTable = new DataTable();
Add method 
DataTable GetBufferDataTable(IEnumerable<Model> models)

2021-06-23 07:58 UTC, sachenko-igor commented on WriteFromCsvToDatabase/Services/ChunkDataLoader.cs
>              var dataTable = new DataTable();
It will make your code a bit slower but more readable

2021-06-23 08:42 UTC, Mih-Mir commented on WriteFromCsvToDatabase/Services/ChunkDataLoader.cs
>              var dataTable = new DataTable();
Is done

2021-06-23 10:09 UTC, sachenko-igor approved these changes

2021-06-23 11:08 UTC, merged